### ISSUE TITLE
[Feature] spring boot, mysql docker 로컬 개발환경 세팅

### ISSUE THREAD

**Issue by bianbbc87** [CSID-DGU/2024-1-OSSP1-togathering-2#1]
### Description

- spring boot, react, mysql dockerfile을 docker-compose로 연결하였다.
- swagger를 세팅해서 api test 준비를 하였다.
- spring boot 파일 구조를 설정하였다.
- api payload를 설정하였다.
- domain 패키지에서 jpa를 세팅하였다.

### ✅ Tasks

- [x] db mysql dockerfile 생성
- [x] spring boot dockerfile 생성
- [x] docker-compose network 연결
- [x] spring boot 파일 디렉토리 설정
- [x] domain entity 설정
- [x] swagger 연결
- [x] nginx 연결
- [x] docker-compose dev, prod로 분리
- [x] application.yml dev, prod로 분리
- [x] 환경변수 설정
- [x] 파일 구조 설정 
- [x] api payload 작성 

### ▪ Etc
백엔드 프로젝트 받아올 시 루트 경로에 .env 파일 가져와서 사용해주세요.
앞으로 prod 버전으로 rds, ec2 연결 할 예정
