### ISSUE TITLE
[FEAT] spring boot, mysql docker 배포 개발 환경 세팅

### ISSUE THREAD

**Issue by bianbbc87** [CSID-DGU/2024-1-OSSP1-togathering-2#3]
### Description

- dockerfile을 이용해서 서버 배포용 개발 환경 설정을 한다.

### ✅ Tasks

- [x] mysql aws rds로 연결
- [x] cors 테스트
- [x] 도메인 등록
- [x] ec2 서버로 배포
- [x] prod 파일 세팅
